version: '3.8'

services:
  voucher-db:
    container_name: mysql-auth
    hostname: mysql-8
    image: mysql:8.0.25
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=auth
    ports:
      - '33062:3306'